Updated Splunk SDK
illumio-shield/illumio-splunk-ta pull request #1
Opened 2023-06-27 05:34 UTC by dhruvilbhatt-crest

2023-06-27 17:40 UTC, dsommerville-illumio requested changes
Thanks, looks good. Can you update `app.conf` to bump the build/launcher versions and add an `[id]` stanza?

I think all other appinspect warnings can be safely ignored.

2023-06-29 10:30 UTC, dhruvilbhatt-crest commented
@dsommerville-illumio Bumped the version to 4.0.0. Since we are maintaining the version in the launcher stanza, the ID stanza is not required.

2023-06-29 10:51 UTC, dsommerville-illumio commented
@dhruvilbhatt-crest - this is not a major version release. Please stick to standard [semantic versioning](https://semver.org/) - this is a backwards-compatible change with no deprecations or additional functionality, so it should just be a patch version bump to 3.2.3.

2023-06-29 10:59 UTC, dsommerville-illumio commented on TA-Illumio/default/app.conf
> +build = 1
This should conform to the previous build format, which seems to be YYYYMMDD

2023-06-29 11:06 UTC, dsommerville-illumio approved these changes
Thanks, looks good.

2023-06-29 11:09 UTC, merged